EID-1550: Add in new pipeline to build Denmark
alphagov/verify-proxy-node pull request #266
Opened 2019-07-17 13:43 UTC by tomrosier

2019-07-18 09:55 UTC, blairboy362 commented
Before this will work you need to add an istio `DestinationRule` and `VirtualService` (follow the `hub-egress-` examples as a template. You'll also need to add an entry for `eidasconnector.test.eid.digst.dk` to `verify-cluster-config`.

Nitpick: the changes look more like a "deploy" than a "build" (title of the PR had me confused for a moment).

2019-07-22 12:27 UTC, instantiator submitted a review, later dismissed

2019-07-24 00:55 UTC, CharlesIC commented
This is good to go. I can't approve because I've pushed to this PR.

2019-07-24 14:04 UTC, blairboy362 submitted a review, later dismissed

2019-07-24 14:05 UTC, blairboy362 commented
@CharlesIC I think you can approve it...I think it only doesn't count for the person that opened (owns) the pull request. I'm sure I've approved PRs I've pushed to in the past...

2019-07-25 11:13 UTC, idrop requested changes

2019-07-25 11:13 UTC, idrop commented on ci/integration/deploy-pipeline.yaml
> +            CONNECTOR_METADATA_FQDN: eidasconnector.test.eid.digst.dk
```suggestion
            CONNECTOR_METADATA_FQDN: eidasconnector.test.eid.digst.dk
            HUB_FQDN: www.integration.signin.service.gov.uk
```
I think the `HUB_FQDN` was added to nl-integration recently, and we should add this too

2019-07-25 11:32 UTC, idrop submitted a review, later dismissed
Good to go

2019-07-25 14:54 UTC, instantiator approved these changes

2019-07-25 14:55 UTC, blairboy362 approved these changes

2019-07-25 15:00 UTC, merged